name: Compatible Jasmine Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        jasmine-version: [2.x, 3.x, 4.x, 5.x]

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Use Node.js 16.x
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm install jasmine@${{ matrix.jasmine-version }} jasmine-core@${{ matrix.jasmine-version }} @types/jasmine@${{ matrix.jasmine-version }}
    - run: npm test
